---
- name: make sure nginx is installed
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: make sure its running
  service:
      name: nginx
      state: started
      enabled: yes

- name: make sure nginx directory exists
  file:
    path: /var/www/angular-deploy
    state: directory
    mode: '0755'

- name: copy angular nginx config
  copy:
     src: "{{ role_path }}/files/default"
     dest: /etc/nginx/sites-available/default
     mode: 644
  notify:
     - restart nginx

- name: confirm site is enabled
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
