---
- hosts: all
  become: yes
  vars:
      ansible_python_interpreter: "/usr/bin/env python"


  roles:
      - {role: nginx, tags: ['nginx']}
      - {role: ded_backend, tags: ['backend']}
      - {role: postgres, tags: ['database']}
