---
- name: install apt-key
  apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add new apt repository for upgraded postgres
  apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main

- name: make sure postgres is installed
  apt:
    name: postgresql-12
    state: latest
    update_cache: yes

- name: make sure its running
  service:
      name: postgresql
      state: started
      enabled: yes
